lerrua/remote-jobs-brazil

- README.md
> Adicionando Raise

- README.md
> Add Pegcar

- README.md
Empresa trabalha com freelas, de acordo com trampo publicado no Trampos http://trampos.co/oportunidades/123132-front-end-developer-freelancer
> Pixedworks

- README.md
Formulário para disponibilização dos dados para registro interno.
> Adicionada empresa Ampla Visão

- README.md
Onyo is a great place to work.
We are hiring mobile (IOS and Android [ native ]) and backend (Python) developers :)
> Adding Onyo

- README.md
> Adding companies from outside Brazil

- README.md
A Free (as in freedom) Software Cooperative
Works with FOSS development
> Adds Colivre

- README.md
> Fix HE:labs name

- README.md
Medicinia supports full remote too :smile:
> Adding Medicinia to the list

- README.md
i would like share and commit a new one company that hire brazilians to work.
> add new multinacional company

- README.md
> Added Lev Interactive to the international employers!

- README.md
> Introduce 10up and Automattic

- README.md
> Adicionando startup Blogo :)

- README.md
> Add Modern Tribe

- README.md
Added the company Repassa in the list and put the char '/' in the end of the line before
> added company repassa

- README.md
> Adds ntxdev as a full remote company :)

- README.md
added teamed.io to the list of companies from outside brazil.
> Added teamed.io

- README.md
Include that company, it's hiring brazilians.
> Clevertech added

- README.md
I sent an email to people@pismo.com.br and Marcelo Parise answer me that this company accepts remote jobs.
> Added Pismo.io brazilian company

- README.md
Company site
http://gravity4.com/
Jobs:
http://gravity4.theresumator.com/
> Adding the Gravity4 Company

- README.md
Unfortunately, this company no longer accepts home-office.
> Removing company that no longer accepts remote workers :(

- README.md
Just adding a new company called Skore, for now they are with open jobs
> Adding Skore brazilian company

- README.md
Myfreecomm was changed to nexaas.
> Changed myfreecomm to nexaas

- README.md
Just adding a new company called Quéz Media as an outside Brazil remote company.
> Add Quéz Media to outside Brazil remote company

- README.md
Cannot connect to http://pixedworks.com/
> Remove Pixedworks

- README.md
CARGOBR - https://cargobr.com/
> Adicionado CARGOBR

- README.md
ref: https://github.com/lerrua/remote-jobs-brazil/pull/83
> Revert "Added Doximity"

- README.md
Fix list2 header with a more semantic phrase.
> Fix list2 header

- README.md
It's true that on some exceptional conditions, they accept some to work remotely... but only while the relocation is not yet concluded.
> Shopify does not accept remote only workers

- README.md
Gupy é uma plataforma que usa Machine Learning para recomendar candidatos para empresa.
> Inclusão da Gupy

- README.md
> Add Magnetis on the list

- README.md
> Update README.md to add VML Brasil

- README.md
It is distributed company that can hire from Brazil, it is part of ConsenSys. The product help lawyers to create, deploy, and edit, next generation legal agreements relying on blockchain technology.
> Added OpenLaw company that hires brazucas

- README.md
Full Tech and Marketing team is remote.
Company was born remote and has been since its foundation in 2016.
> Adding bxblue

- README.md
DB1 is a company that is located in Maringá, Paraná, Brazil and hires remote workers.
> Added DB1 Global Software

- README.md
I know some Brazilians guys that work remotely for Telnyx.
> Add Telnyx

- README.md
A Collabora é uma consultoria de Open Source anglo canadense que contrata pessoas desenvolvedoras do mundo inteiro e atualmente conta com 7 brasileiros espalhados pelo Brasil :)
> Add Collabora jobs to the list

- README.md
Add Close.io
jobs: https://jobs.lever.co/close.io/
> Add Close.io

- README.md
Hi there!
We'd like to add our company as Brazilian Companies that hires remote workers.
Thanks for this project!
> adds PLING

- README.md
Deleted the Happy Bear Software company from the list, because it says on their website that they are closed for business; 
There is a broken link for the Titansgroup website.
> Updates on list of companies.

- README.md
Empresa americana, mas contratamos remoto em vários países, dos quais Brasil incluso
> Add Gruntwork

- README.md
Empresa brasileira que inclusive criou uma [ferramenta open source](https://github.com/ResultadosDigitais/matrix) para trabalho remoto.
> Add Resultados Digitais

- README.md
Stone are hiring people for remote work for `INOVAÇÃO` team
more details check the link: https://jobs.kenoby.com/enter.stone
> add stone pagamentos

- README.md
M4U is a company focused on credit card processing for telecom companies. The headquarter is located in Rio de Janeiro but the company has a 100% remote policy https://www.m4u.com.br .
> Add M4U in the list

- README.md
Invillia is a company from Araraquara/SP with more than 100 developers working remotely.
> Added Invillia

- README.md
e-Core is partially remote, you can see in the open opportunities that they have remote jobs:
https://e-core.com/pt/carreiras/oportunidades/
> Add e-Core

- README.md
We have some remote positions for Senior Engineers working remotely from Brazil, eg: https://jobs.lever.co/loadsmart/ef41cd47-9b1b-4a67-9bf5-7c4ed2c865d1
> Add Loadsmart to list of companies that hire brazilians to work remotely

- README.md
Somos uma empresa de Porto Alegre mas temos pessoas trabalhando remotamente conosco em São Paulo, Goiás, Espírito Santo e cidades do interior do Rio Grande do Sul.
Atualmente temos uma posição aberta para Senior Software Engineer:
https://github.com/Superplayer/jobs/issues/12
> Adding Superplayer & Co to the list of brazilian companies

- README.md
Add Data Science Brigade to list of companies that hire Brazilians to work remotely.
> Add Data Science Brigade to list of companies

- README.md
Most people once a week home office and some people 100% home office.
> Add amparo saúde

- README.md
They are HR-like company that haves BR office and help US companies to hire brazillian Devs
> Adds RocketPower.io

- README.md
Adding Hurb.com's Linked-In page as landing page.
> Adding hurb.com

- README.md
- Grupo MContigo S.L
- Coodesh.com
> add my companies (100% remote)

- README.md
Eu trabalho remotamente na OSF, pode ser q não tenham vagas agora durante a crise do corona vírus, mas é uma empresa multinacional que contrata remotamente no Brasil.
> Added OSF company

- README.md
Somos pessoas incríveis transformando a prestação de serviços em algo incrivelmente fácil ❤︎
Nosso produto é um SaaS (Software as a service) para empresas que possuem prestadores de serviços externos.
Entregamos controle, organização e melhor relacionamento com o cliente para empresas de Climatização, Segurança eletrônica, Telecom, Provedores de internet, Montadoras de móveis, Empresas de limpeza, enfim, qualquer empresa que possui uma equipe de campo para realização de serviços.
> :blue_heart: Adicionando a Field Control na lista

- README.md
Devido a pandemia surgiu a necessidade do trabalho remoto.
O trabalho remoto deu tão certo, que a empresa aderiu ao formato no setor de desenvolvimento.
> Add Sysmo to the list

- README.md
Clicksign já tem bastante tempo de mercado e sempre trabalhou com a cultura Remote First
> Add ClickSign to the list

- README.md
https://www.indeedjobs.com/aftersale/jobs
> Adds "aftersale"

- README.md
https://boards.greenhouse.io/truelogic
> Add Truelogic

- README.md
Movidesk | https://www.movidesk.com/trabalhe-conosco
> Add Movidesk

- README.md
I added a company on the list. The name of this company is ClubHouse.
> Added ClubHouse company

- README.md
empresa que aceita trabalho remoto de programação.
> empresa com trabalho remoto evolux

- README.md
> Acesso Digital

- README.md
> Add Letras

- README.md
> Added AchieveTestPrep 

- README.md
> Adds Ferreri to the list

- README.md
- Add Cortex Intelligence | https://cortex-intelligence.com/, a remote-first Brazilian company.
- Remove an extra space from `Amparo Saúde` url
> Add Cortex Intelligence

- README.md
> Add ww.vnda.com.br

- README.md
203 Pixels 
Before: http://203pixels.com.br/ not working
After: https://www.linkedin.com/company/203-pixels/
a2c
Before: https://www.a2c.com.br/
After: https://www.briviagroup.com.br/
> changing url that doesn't work for correct url

- README.md
ABOUT US
VTEX is the only multitenant commerce platform capable of unifying experiences in all sales channels. With a robust solution, scalable cloud infrastructure and powerful tooling, our platform accelerates the transformation of complex operations.
More than 2900 renowned companies of varying sizes and segments, with operations in 42 countries and in global expansion, have at VTEX the solution for the online sale of their products, among them major names such as Sony, Motorola, Walmart, Whirlpool, Coca-Cola, Stanley Black & Decker, and Nestlé.
> Adding VTEX

- README.md
I currently work at this company as a Java software developer and it is a great place to work remotely.
> Add Objective to Brazilian Companies

- README.md
- Changed our domain and company name capitalisation
> Change our domain and company name capitalisation

- README.md
I work from Brazil at Meltwater as a contractor :)
> Add Meltwater

- README.md
line 62. FCamara is a brazilian Software and Web Application Development company. They have a nice trainee program and its up to the employee the choice on working remotely or not.
> Adding FCamara

- README.md
- Add Compasso UOL, is my remotely current job, in this company all developer works are remotely, is a company of UOL
https://compassouol.com/
> Add Compasso UOL

- README.md
GFT is present in Brazil with some offices in SP and Curitiba, I worked there for almost one year in a full remote position (they are actively hiring and most of the positions are remote).
> Add GFT into the list

- README.md
Thanks for this great project!
> docs: add ioasys

- README.md
Added: CI&T a Brazilian company who have a lot of opportunities to work remotly.
> Add: CI&T a Brazilian company who have a lot of opportunities to work remotly.

- README.md
> Added Atta Franchising

- README.md
> docs: add juntossomosmais

- README.md
Hello, I am sending over BEON Tech Studio, a Latin American company that provides remote jobs to Brazilian developers.
> Added BEON Tech: we provide remote opportunities for Brazilian devs

- README.md
Contribuindo com a empresa Afya que contrata full remoto ou híbrido
> add afya company

- README.md
> Added Iteris Consultoria

- README.md
Empresa fechou e demitiu todo o time de devs.
> Remove Crave Food

- README.md
Popstand is a Los Angeles based web and mobile software development company with decades of experience. We are well-versed in the art of the startup and build minimum viable products (MVPs) that people love to use.
[site](https://popstand.com/)
> add Popstand company

- README.md
Changing READ.ME file, adding Fanatee, Icaro Tech and Wex to list.
> Adding Fanatee, Icaro Tech and Wex

- README.md
Beyond is looking for developers, product owners, software architects and UX designers to improve the brazilian financial market
> Adds Beyond Soluções

- README.md
Added Raízen on line 146. One of biggest companies in Brazil w/ many opportunities
> Adding Raízen

- README.md
> removing high stake academy

- README.md
> removing maption for inactivity

- README.md
I'm adding the company I'm currently part of, Bridge & Co. It's fully remote
> New Company Added
